// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "not_found_title": "Not Found",
  "not_found_button": "Go Back",
  "back_to_top": "Back to top",
  "user_clicks_count": "Picked by {amount} users this month",
  "product_estimated_price": "Estimated Price"
};
export default messages;